# map_name: "torino"
# map_name: "levine_blocked"
# map_name: "berlin"
map_name: "porto"
# map_name: "race_track"
map_ext: ".png"
# map_ext: ".pgm"

# starting positions for vehicle
sx: 0.0
sy: 0

stheta: 0  # porto
# stheta: 2.5 # torino

vehicle_path: "Data/Vehicles/"

mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158

max_v: 7
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

plan_frequency: 1
v_min_plan: 1
max_time: 50

kernel_path: "Data/Kernels/"
kernel_mode: "viab"
n_phi: 41
n_modes: 5
phi_range: 6.28
discrim_block: 1 
discrim_phi: 0.0
n_dx: 80
# time_step: 0.1
kernel_time_step: 0.3

test_n: 2

EvalName: "Safety"
