# map data
# map_name: "example_map"
# map_name: "vegas"
# map_name: "torino"
# map_name: "levine_blocked"
# map_name: "berlin"
map_name: "porto"
# map_name: "race_track"
map_ext: ".png"
# map_ext: ".pgm"

# starting positions for vehicle
sx: 0.0
sy: 0

stheta: 0  # porto
# stheta: 2.5 # torino

vehicle_path: "Vehicles/"

mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158
force_f: 0.9

max_v: 7
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

lookahead: 0.82
v_gain: 0.9

plan_frequency: 1
v_min_plan: 1
max_time: 50

cross_track_scale: 1  # scaled val for cth error


kernel_path: "Kernels/"
track_kernel_path: "std"
n_phi: 41
n_modes: 5
phi_range: 6.28
discrim_block: 1 
discrim_phi: 0.1
n_dx: 80
# time_step: 0.1
kernel_time_step: 0.3

test_n: 10
train_n: 20000
n_beams: 20
range_finder_scale: 5
h_size: 100

